import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[shell]
program="/bin/tmux"

[window]
padding={ x=10, y=10 }
class={ instance="Alacritty", general="Alacritty" }
opacity=0.9

[font]
normal={family="JetBrainsMono NF", style="Regular"}
bold={family="JetBrainsMono NF", style="Bold"}
italic={family="JetBrainsMono NF", style="Italic"}
bold_italic={family="JetBrainsMono NF", style="Bold Italic"}
size=11

[selection]
save_to_clipboard=true

[env]
TERM = "xterm-256color"
